// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc5f332S16XbdGUWBJwGSXzbJD4eVSDe0',
    appId: '1:654253936390:web:ad5add8067244a85d41887',
    messagingSenderId: '654253936390',
    projectId: 'unicalendar-b1e96',
    authDomain: 'unicalendar-b1e96.firebaseapp.com',
    storageBucket: 'unicalendar-b1e96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRKQFyN_Cs3eqtroKEIL-QMu6E7_MemSo',
    appId: '1:654253936390:android:cce2620e28d6448fd41887',
    messagingSenderId: '654253936390',
    projectId: 'unicalendar-b1e96',
    storageBucket: 'unicalendar-b1e96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj2tjpZ15xdjzXXXCsy1HuSxjcrzzzZaY',
    appId: '1:654253936390:ios:133e07c2e11a3aefd41887',
    messagingSenderId: '654253936390',
    projectId: 'unicalendar-b1e96',
    storageBucket: 'unicalendar-b1e96.firebasestorage.app',
    iosClientId: '654253936390-2q4ncajcv7r9i9n17d8t125ftmh2ijcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj2tjpZ15xdjzXXXCsy1HuSxjcrzzzZaY',
    appId: '1:654253936390:ios:133e07c2e11a3aefd41887',
    messagingSenderId: '654253936390',
    projectId: 'unicalendar-b1e96',
    storageBucket: 'unicalendar-b1e96.firebasestorage.app',
    iosClientId: '654253936390-2q4ncajcv7r9i9n17d8t125ftmh2ijcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc5f332S16XbdGUWBJwGSXzbJD4eVSDe0',
    appId: '1:654253936390:web:664ad00f72d70f00d41887',
    messagingSenderId: '654253936390',
    projectId: 'unicalendar-b1e96',
    authDomain: 'unicalendar-b1e96.firebaseapp.com',
    storageBucket: 'unicalendar-b1e96.firebasestorage.app',
  );
}
